<?php
	require_once(PWD_ADHERENT_V2.'configuration.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include(PWD_ADHERENT_V2.'entete.php');?>
</head>
<body>
<?php include(PWD_ADHERENT_V2.'debut.php');?>
<div id="conteneur">
  <p>Le site <?php print($_SERVER['HTTP_HOST']);?> est &eacute;dit&eacute; par la soci&eacute;t&eacute;:</p>
  <p>SARL AICOM<br />
    117, rue de la R&eacute;publique<br />
    83210 La Farl&egrave;de<br />
    FRANCE<br />
  SIRET: 392 485 892 00039<br />
  Contact: <a href="mailto:<?php print(urlencode(ini_get('sendmail_from')));?>"><?php print(ini_get('sendmail_from'));?></a><br />
  </p>
  <p>Les internautes utilisant le site <?php print($_SERVER['HTTP_HOST']);?> sont ci-apr&egrave;s d&eacute;sign&eacute;s: Utilisateur(s).</p>
  <h1>Production du contenu &eacute;ditorial</h1>
  <p><?php print($_SERVER['HTTP_HOST']);?> propose un contenu &eacute;ditorial d'information ax&eacute; sur la location immobili&egrave;re.</p>
  <p> Le service de recherche <?php print($_SERVER['HTTP_HOST']);?> collecte ses informations sur l'ensemble du Web afin de mettre &agrave; la disposition des internautes et des abonn&eacute;s de <?php print($_SERVER['HTTP_HOST']);?> le maximum d'annonces et d'indications utiles et n&eacute;cessaires &agrave; la recherche et &agrave; l'obtention d'un logement. </p>
  <h1>Fonctionnements et responsabilit&eacute;s</h1>
  <p><?php print($_SERVER['HTTP_HOST']);?> est un support de recherche et de mise &agrave; disposition de petites annonces et non un interm&eacute;diaire dans les transactions. Cela signifie que la responsabilit&eacute; de <?php print($_SERVER['HTTP_HOST']);?> ne saurait &ecirc;tre engag&eacute;e directement ou indirectement dans les transactions qui ob&eacute;issent aux r&egrave;gles g&eacute;n&eacute;rales du code civil (art.1641 et suivants). La parution et la mise &agrave; jour des annonces sont sous la seule responsabilit&eacute; des annonceurs.</p>
  <h2>Les abonnements payants</h2>
  <p><?php print($_SERVER['HTTP_HOST']);?> propose &agrave; ses Utilisateurs une consultation &agrave; la session et des abonnements payants hebdomadaires et bimensuels.</p>
  <dl>
    <dt> Consultation &agrave; la session:</dt>
    <dd>Avec une saisie d'un nom et d'un mot de passe l'utilisateur indique ses informations de connexion et ouvre une session pour acc&eacute;der au service <?php print($_SERVER['HTTP_HOST']);?>.
      En pratique, la session se termine lorsqu&rsquo;il y a une absence d&rsquo;action sur le site pendant plus de 30 minutes.</dd>
    <dt>Abonnement &agrave; la dur&eacute;e hebdomadaire et bimensuel.</dt>
    <dd>Avec une saisie d'un nom et d'un mot de passe l'utilisateur indique ses informations de connexion, et acc&egrave;de sans limitation du nombre de fois, 24h/24h pendant toute la dur&eacute;e de l&rsquo;abonnement au service <?php print($_SERVER['HTTP_HOST']);?>.</dd>
  </dl>
  <p>La consultation est limit&eacute;e &agrave; <?php print($preference->annonce_vue_jour);?> annonces par tranche de 24h  et par compte  cr&eacute;&eacute;.</p>
  <p>Le service <?php print($_SERVER['HTTP_HOST']);?> permet &agrave; l'Utilisateur de consulter les annonces de location avec les coordonn&eacute;es t&eacute;l&eacute;phoniques des propri&eacute;taires ou de leur mandataire. L'abonnement est pay&eacute; par code audiotel, carte de paiement, ch&egrave;que ou directement pr&eacute;lev&eacute; par le fournisseur d&rsquo;acc&egrave;s internet de l&rsquo;utilisateur. L'abonnement ne peut se faire qu'apr&egrave;s paiement complet et effectif par l'Utilisateur. Les prix indiqu&eacute;s sont par d&eacute;faut toutes taxes comprises et n'incluent pas les frais correspondants &agrave; la connexion Internet qui restent &agrave; la charge exclusive de l'Utilisateur. A tout moment et sans en communiquer la raison aux utilisateurs, <?php print($_SERVER['HTTP_HOST']);?> reste libre de modifier les tarifs de ses abonnements. Chaque utilisateur se voit remettre au moment de la souscription &agrave; son abonnement une autorisation d'acc&egrave;s valable durant toute la dur&eacute;e de ce dernier. Les autorisations d'acc&egrave;s sont &agrave; usage strictement personnel: l'Utilisateur s'interdit par cons&eacute;quent de divulguer &agrave; toute personne tierce l'autorisation d'acc&egrave;s qui lui a &eacute;t&eacute; remis et mettra en &oelig;uvre les moyens n&eacute;cessaires pour conserver le caract&egrave;re personnel de cette autorisation d'acc&egrave;s. En cas de violation manifeste de ces obligations, <?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve la possibilit&eacute;:
  <ul>
    <li> de supprimer sans pr&eacute;avis, sans formalit&eacute; et sans indemnit&eacute; pour le contrevenant l'autorisation d'acc&egrave;s divulgu&eacute;e par ce dernier,</li>
    <li>d'ester en justice contre le contrevenant</li>
    <li>d'interdire au contrevenant l'acc&egrave;s au site ou &agrave; une de ses rubriques.</li>
    </li>
    </li>
  </ul>
  <p>La perte d'une autorisation d'acc&egrave;s attribu&eacute;e &agrave; un Utilisateur rel&egrave;ve de l'enti&egrave;re responsabilit&eacute; de ce dernier. Le cas &eacute;ch&eacute;ant, <?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve le droit d'accepter ou de refuser l'octroi d'un nouvel acc&egrave;s personnel. Plusieurs modes de paiement (Audiotel, Carte bancaire, ch&egrave;que) sont propos&eacute;s &agrave; l'Utilisateur qui accepte les conditions financi&egrave;res et de facturation propos&eacute;es par ces derniers. <?php print($_SERVER['HTTP_HOST']);?> reste libre de supprimer, d&eacute;finitivement ou temporairement, de suspendre ou de modifier, l'une ou l'autre des solutions de paiement propos&eacute;es. En cas de paiement frauduleux, <?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve la possibilit&eacute; de supprimer l'usage de l'autorisation d'acc&egrave;s. La description des moyens de paiement n'est ni exhaustive ni d&eacute;finitive, et <?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve le droit de supprimer, de modifier ou d'ajouter des services ou de nouvelles caract&eacute;ristiques, dans le seul but d'am&eacute;liorer la qualit&eacute; de ses abonnements ou de ses rubriques. L'Utilisateur ne dispose pas d'un droit de r&eacute;tractation dans le cadre des abonnements et ce en conformit&eacute; avec l'exception mentionn&eacute;e &agrave; l'Article L. 121-20-2 du Code de la Consommation. La responsabilit&eacute; de <?php print($_SERVER['HTTP_HOST']);?> sera limit&eacute;e au montant du prix des Services payants souscrits. L'Utilisateur reconna&icirc;t et accepte que le contenu des rubriques du site <?php print($_SERVER['HTTP_HOST']);?> soit prot&eacute;g&eacute; par le droit de la propri&eacute;t&eacute; intellectuelle, le droit des marques, le droit des brevets ou tout autre droit reconnu par la l&eacute;gislation en vigueur. L'Utilisateur n'est pas autoris&eacute; &agrave; copier, utiliser, reproduire, distribuer tout ou partie du Contenu du site <?php print($_SERVER['HTTP_HOST']);?> sur quelconque support &agrave; titre on&eacute;reux ou gratuit. L'Utilisateur n'est pas autoris&eacute; &agrave; cr&eacute;er et exploiter toutes &oelig;uvres d&eacute;riv&eacute;es &agrave; partir du contenu des rubriques du site <?php print($_SERVER['HTTP_HOST']);?>. En cas de violation, <?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve la possibilit&eacute;:
  <ul>
    <li> De supprimer sans pr&eacute;avis, sans formalit&eacute; et sans indemnit&eacute; pour le contrevenant l'autorisation d'acc&eacute;s remis &agrave; ce dernier,</li>
    <li>D'ester en justice contre le contrevenant,</li>
    <li>D'interdire au contrevenant l'acc&egrave;s au site ou a une de ses rubriques</li>
  </ul>
  <h1>La protection de la vie priv&eacute;e et des donn&eacute;es personnelles</h1>
  <h2>Envoi de mail</h2>
  <p>En acceptant les conditions g&eacute;n&eacute;rales, en remplissant les renseignements demand&eacute;s et en cochant les cases appropri&eacute;es, l'utilisateur confirme devenir utilisateur membre de <?php print($_SERVER['HTTP_HOST']);?>, &agrave; ce titre il pourra recevoir de l'actualit&eacute; (texte et images) et des propositions commerciales &eacute;manant des partenaires commerciaux de la soci&eacute;t&eacute; <?php print($_SERVER['HTTP_HOST']);?> sur l'adresse email que l'utilisateur a indiqu&eacute;. A tout moment et &agrave; chaque r&eacute;ception de mail &eacute;manant de la soci&eacute;t&eacute; <?php print($_SERVER['HTTP_HOST']);?> ou des sites partenaires, l'utilisateur membre aura la possibilit&eacute; de se d&eacute;sinscrire par le biais d'un lien de d&eacute;sabonnement ou en faisant la demande par mail.</p>
  <h2>Loi Informatique et libert&eacute;s</h2>
  <p>En application de la loi n&deg;78-17 du 6 janvier 1978 relative &agrave; l'informatique, aux fichiers et aux libert&eacute;s, l'Utilisateur dispose des droits d'opposition (art.26 de la loi), d'acc&egrave;s (art.34 &agrave; 38 de la loi), et de rectification (art.36 de la loi) des donn&eacute;es le concernant. Ainsi, l'Utilisateur peut exiger que soient rectifi&eacute;es, compl&eacute;t&eacute;es, clarifi&eacute;es, mises &agrave; jour ou effac&eacute;es les informations le concernant qui sont inexactes, incompl&egrave;tes, &eacute;quivoques, p&eacute;rim&eacute;es ou dont la collecte ou l'utilisation, la communication ou la conservation est interdite.</p>
  <h2>La s&eacute;curit&eacute; des &eacute;changes</h2>
  <p> <?php print($_SERVER['HTTP_HOST']);?> s'engage &agrave; prendre toutes les mesures juridiques et techniques pour s&eacute;curiser les &eacute;changes. A ce titre, <?php print($_SERVER['HTTP_HOST']);?> s'engage &agrave; une obligation de moyen pour bloquer les d&eacute;tournements de donn&eacute;es et &agrave; respecter les r&eacute;glementations applicables. N&eacute;anmoins, les Utilisateurs du site connaissent les particularit&eacute;s techniques du r&eacute;seau Internet et les risques aff&eacute;rents. Par cons&eacute;quent, <?php print($_SERVER['HTTP_HOST']);?> ne peut garantir &agrave; ses Utilisateurs que les donn&eacute;es &eacute;chang&eacute;es via les services propos&eacute;s par <?php print($_SERVER['HTTP_HOST']);?> ne soient pas r&eacute;colt&eacute;s de fa&ccedil;on frauduleuse par des tiers.</p>
  <h2>Droits de propri&eacute;t&eacute; intellectuelle</h2>
  <p>Tous les documents, informations textes, graphiques, images, photographies ou tous autres contenus diffus&eacute;s sur le site font l'objet d'une protection au titre du droit d'auteur et de la propri&eacute;t&eacute; intellectuelle pour le monde entier. En cons&eacute;quence, et conform&eacute;ment au Code de la Propri&eacute;t&eacute; Intellectuelle fran&ccedil;ais, seule l'utilisation pour un usage privatif est autoris&eacute;e, sous r&eacute;serve de dispositions l&eacute;gales ou r&eacute;glementaires applicables plus restrictives. Toute autre utilisation est susceptible d'&ecirc;tre qualifi&eacute;e de contrefa&ccedil;on et sanctionn&eacute;e par les tribunaux fran&ccedil;ais comp&eacute;tents, sauf autorisation expresse pr&eacute;alable et &eacute;crite de <?php print($_SERVER['HTTP_HOST']);?>. En cons&eacute;quence toute reproduction, alt&eacute;ration ou modification de quelque &eacute;l&eacute;ment du site que ce soit est interdite. <?php print($_SERVER['HTTP_HOST']);?> est titulaire de droits concernant certaines donn&eacute;es prot&eacute;g&eacute;es par l'autorisation d'acc&egrave;s de la propri&eacute;t&eacute; intellectuelle. Il en est notamment ainsi pour la marque &quot;Localerte&quot;, sa charte graphique, sa base de donn&eacute;es. Par cons&eacute;quent, l&rsquo;exploitation &agrave; titre gratuit ou on&eacute;reux, de tout ou partie de ces donn&eacute;es sans le consentement expresse de <?php print($_SERVER['HTTP_HOST']);?> est interdite.</p>
  <h2>Acc&egrave;s au site et disponibilit&eacute; des services</h2>
  <p><?php print($_SERVER['HTTP_HOST']);?> se r&eacute;serve le droit de refuser, unilat&eacute;ralement et sans notification pr&eacute;alable, &agrave; tout Utilisateur l'acc&egrave;s &agrave; tout ou partie du Site <?php print($_SERVER['HTTP_HOST']);?>. Une telle d&eacute;cision pourrait notamment &ecirc;tre prise en cas de non-respect des pr&eacute;sentes conditions g&eacute;n&eacute;rales par un Utilisateur. <?php print($_SERVER['HTTP_HOST']);?> dispose d'une obligation de moyens en terme d'accessibilit&eacute; de service et met en place les structures n&eacute;cessaires pour rendre le site <?php print($_SERVER['HTTP_HOST']);?> accessible 7 jours sur 7 et 24 heures sur 24. N&eacute;anmoins, <?php print($_SERVER['HTTP_HOST']);?> peut suspendre l'acc&egrave;s sans pr&eacute;avis, notamment pour des raisons de maintenance et de mises &agrave; jour. <?php print($_SERVER['HTTP_HOST']);?> n'est en aucun cas responsable des &eacute;ventuels pr&eacute;judices qui peuvent en d&eacute;couler pour l'Utilisateur ou tout tiers. <?php print($_SERVER['HTTP_HOST']);?> peut &agrave; tout moment supprimer tout ou partie de ses services, de ses rubriques et en modifier leur teneur notamment pour des raisons techniques, et cela sans pr&eacute;avis.</p>
  <h2>Droit applicable</h2>
  <p>Les conditions g&eacute;n&eacute;rales du site <?php print($_SERVER['HTTP_HOST']);?> sont soumises au droit fran&ccedil;ais. La soci&eacute;t&eacute; AICOM est une soci&eacute;t&eacute; de droit fran&ccedil;ais. La loi applicable aux relations contractuelles est la loi fran&ccedil;aise.</p>
  <h1>H&eacute;bergements</h1>
  <p>L'h&eacute;bergement est assur&eacute; par la soci&eacute;t&eacute; <a href="http://www.aicom-multimedia.fr">AICOM</a>.</p>
</div>
<?php include(PWD_ADHERENT_V2.'fin.php');?>
</body>
</html>
